const appGlobals = Object.fromEntries(
  [
    "DatasightDom",
    "DatasightSearchHelpers",
    "DatasightStore",
    "STARTER_CONFIG",
    "messagesEl",
    "inputEl",
    "sendBtn",
    "stopBtn",
    "welcomeEl",
    "sidebar",
    "sessionId",
    "isStreaming",
    "currentAssistantBubble",
    "currentAssistantText",
    "selectedTable",
    "allQueries",
    "schemaData",
    "lastSql",
    "lastPlotlySpec",
    "lastToolName",
    "lastToolMeta",
    "confirmSqlEnabled",
    "explainSqlEnabled",
    "clarifySqlEnabled",
    "showCostEnabled",
    "sessionTotalCost",
    "pendingConfirmResolve",
    "sessionQueries",
    "pinnedItems",
    "pinnedIdCounter",
    "currentView",
    "fullscreenCardId",
    "selectedCardIdx",
    "currentAbortController",
    "pendingStarterAction",
    "schemaSearchQuery",
    "recentProjectsCache",
    "commandPaletteOpen",
    "commandPaletteResults",
    "commandPaletteSelectedIdx",
    "tablePreviewCache",
    "columnStatsCache",
    "bookmarksCache",
    "reportsCache",
    "conversationsCache",
    "recipesCache",
    "measureEditorCatalog",
    "currentProjectPath",
    "projectLoaded",
    "explorePaths",
    "dashboardColumns",
    "llmConnected",
    "isEphemeralSession",
    "exportMode",
    "exportExcludeIndices",
    "shortcutsModalOpen",
    "scorePaletteResult",
    "highlightMatch",
    "getVisibleSchemaEntries",
    "sanitizeHtml",
    "sanitizeMarkdown",
    "renderMarkdownInto",
    "bindInteractiveBubbleActions",
    "bindSidebarListActions",
    "addAssistantHtml",
    "fetchJson",
    "clearSchemaInsightCaches",
    "clearSchemaSearchState",
    "clearSavedItemCaches",
    "COPY_SVG",
    "PAGE_SIZE",
    "TRASH_SVG",
    "_makeCopyBtn",
    "_makeDeleteBtn",
    "addCopyButtons",
    "addDashboardItemAt",
    "addDashboardNote",
    "addDashboardSection",
    "addFilesFromSidebar",
    "addExplorePath",
    "addExportCheckboxes",
    "addMessage",
    "addTypingIndicator",
    "applyMeasureBuilderSelection",
    "applyPage",
    "applyTheme",
    "askAboutColumn",
    "askAboutTable",
    "bindAppEvents",
    "bindTableEvents",
    "bookmarkQuery",
    "broadcastThemeToDashboard",
    "buildSourceMeta",
    "clearAllBookmarks",
    "clearAllConversations",
    "clearAllReports",
    "clearChat",
    "clearChatForProjectSwitch",
    "closeCommandPalette",
    "connectLlmFromLanding",
    "createDashboardInsertControl",
    "deleteBookmark",
    "deleteElement",
    "deleteReport",
    "deleteUserBlock",
    "doExport",
    "doLoadProject",
    "editReport",
    "ensureRecentProjectsLoaded",
    "escapeHtml",
    "executeCommandPaletteResult",
    "exitCardFullscreen",
    "exploreFromInput",
    "exportDashboard",
    "exportTableCsv",
    "extractClarifyOptions",
    "filterQueries",
    "filterTable",
    "finalize",
    "finalizeAssistantBubble",
    "focusTableInSidebar",
    "formatCost",
    "getCommandPaletteResults",
    "getMultiSelectValues",
    "goToPage",
    "handleExplanationDone",
    "handleSSEEvent",
    "handleSchemaSearchInput",
    "handleSqlConfirm",
    "handleSqlRejected",
    "handleSubmit",
    "handleSuggestions",
    "handleToken",
    "handleToolDone",
    "handleToolResult",
    "handleToolStart",
    "hideExportBar",
    "hideLanding",
    "hideSavePopover",
    "hideShortcutsModal",
    "initLanding",
    "insertMeasureOverride",
    "landingChooseStarter",
    "landingExplore",
    "landingOpenProject",
    "landingOpenRecentProject",
    "loadBookmarks",
    "loadConversation",
    "loadConversations",
    "loadDashboard",
    "loadLlmSettings",
    "loadMeasureOverridesEditor",
    "loadProjectFromList",
    "loadProjectHealth",
    "loadQueries",
    "loadRecentProjects",
    "loadRecipes",
    "loadReports",
    "loadSchema",
    "loadSettings",
    "maybeRunPendingStarter",
    "onLandingProviderChange",
    "onLlmProviderChange",
    "openColumnStatsInSidebar",
    "openCommandPalette",
    "openMeasureOverrideEditorForCard",
    "openMeasureEditorModal",
    "openProjectFromInput",
    "openProjectHealthPanel",
    "openProjectsPanel",
    "openSidebarSection",
    "paginateTable",
    "pinResult",
    "populateMeasureBuilderTables",
    "populateMeasureOverrideBuilder",
    "populateWeightColumnOptions",
    "previewTable",
    "previewTableInSidebar",
    "promptLlmConfigIfNeeded",
    "removeExplorePath",
    "removeExportCheckboxes",
    "removeRecentProject",
    "renderBookmarks",
    "renderCommandPalette",
    "renderConversations",
    "renderDashboard",
    "renderDatasetOverview",
    "renderDimensionOverview",
    "renderExploreFilesList",
    "renderMeasureOverview",
    "renderOverviewList",
    "renderOverviewMetric",
    "renderQualityOverview",
    "renderQueries",
    "renderQueryHistory",
    "renderRecipes",
    "renderReports",
    "renderSchemaQuickActions",
    "renderSourceDetails",
    "renderStarterActions",
    "renderTables",
    "renderTrendOverview",
    "resetMeasureBuilderForm",
    "respondSqlConfirm",
    "restoreCollapsedSections",
    "restoreSession",
    "runInspectAction",
    "runReport",
    "runStarterAction",
    "runStarterFollowup",
    "sanitizeHtml",
    "saveDashboard",
    "saveFromPopover",
    "saveLlmSettings",
    "saveMeasureOverrides",
    "setMeasureEditorTab",
    "saveReport",
    "scrollToBottom",
    "sendExample",
    "sendMessage",
    "setDashboardColumns",
    "setMeasureEditorState",
    "setMultiSelectValues",
    "showExportBar",
    "showLanding",
    "showSavePopover",
    "showShortcutsModal",
    "showToast",
    "showWelcome",
    "slugify",
    "sortTable",
    "startExplore",
    "stopGeneration",
    "summarizeDataset",
    "switchView",
    "syncChartScales",
    "toggleCardFullscreen",
    "toggleClarifySql",
    "toggleConfirmSql",
    "toggleColumnStats",
    "toggleExplainSql",
    "toggleExportMode",
    "toggleProjectsPanel",
    "toggleRightPanel",
    "toggleSetting",
    "toggleSettingsPanel",
    "toggleShowCost",
    "toggleSidebar",
    "toggleSidebarSection",
    "toggleTable",
    "toggleTheme",
    "unpinItem",
    "updateMeasureEditorSummary",
    "updateCommandPaletteResults",
    "updateCostDisplay",
    "updateDashboardBadge",
    "updateInspectScopeLabel",
    "updateMeasureBuilderMode",
    "updateSessionIndicator",
    "updateSettingsButtons",
    "updateSqlDisplay",
    "useQuery",
    "useRecipeElement",
    "useRecipePrompt",
    "validateMeasureOverrides",
    "closeMeasureEditorModal",
  ].map(name => [name, "readonly"]),
);

export default [
  {
    files: ["src/datasight/web/static/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        fetch: "readonly",
        console: "readonly",
        navigator: "readonly",
        crypto: "readonly",
        requestAnimationFrame: "readonly",
        setTimeout: "readonly",
        URL: "readonly",
        Blob: "readonly",
        TextDecoder: "readonly",
        module: "readonly",
        // Libraries loaded via CDN
        marked: "readonly",
        hljs: "readonly",
        DOMPurify: "readonly",
        ...appGlobals,
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { vars: "local", args: "none" }],
      "no-redeclare": "off",
      "eqeqeq": ["warn", "smart"],
      "no-debugger": "error",
      "no-duplicate-case": "error",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-constant-condition": "warn",
    },
  },
];
