# ruff: noqa: F401, F403, F405
"""CLI command module."""

from datasight import cli as cli_root
from datasight.cli import *  # noqa: F403
from datasight.cli import (
    _build_metric_table,
    _build_profile_detail_table,
    _build_sql_script,
    _configure_logging,
    _current_db_settings_or_none,
    _default_chart_extension,
    _default_data_extension,
    _emit_ask_result,
    _emit_cli_provenance,
    _epilog,
    _fmt_dist,
    _format_profile_value,
    _iter_sql_tool_results,
    _load_batch_entries,
    _load_recipe_entries,
    _load_schema_info_for_project,
    _prepare_web_runtime,
    _print_sql_queries,
    _question_table_prefix,
    _render_dimensions_markdown,
    _render_distribution_markdown,
    _render_doctor_markdown,
    _render_integrity_markdown,
    _render_measures_markdown,
    _render_profile_markdown,
    _render_quality_markdown,
    _render_recipes_markdown,
    _render_trends_markdown,
    _render_validation_markdown,
    _resolve_db_path,
    _resolve_settings,
    _sanitize_sql_identifier,
    _slugify_filename,
    _sql_comment_lines,
    _validate_batch_entry,
    _validate_settings_for_llm,
    _write_batch_result_files,
    _write_or_print,
)


def create_llm_client(*args, **kwargs):
    return cli_root.create_llm_client(*args, **kwargs)


async def _run_ask_pipeline(*args, **kwargs):
    return await cli_root._run_ask_pipeline(*args, **kwargs)


@click.command(
    name="log",
    epilog=_epilog(
        """
        Examples:

            datasight log
            datasight log --tail 50 --full
            datasight log --errors
            datasight log --cost
            datasight log --sql 1
        """
    ),
)
@click.option(
    "--project-dir",
    type=click.Path(exists=True),
    default=".",
    help="Project directory containing query_log.jsonl.",
)
@click.option("--tail", "tail_n", type=int, default=20, help="Show last N entries (default: 20).")
@click.option("--errors", is_flag=True, help="Show only failed queries.")
@click.option("--full", is_flag=True, help="Show full SQL and user question.")
@click.option("--cost", is_flag=True, help="Show LLM cost summary.")
@click.option(
    "--sql",
    "sql_index",
    type=int,
    default=None,
    help="Print raw SQL for query # (shown in the # column). Ready to copy-paste.",
)
def log_cmd(project_dir, tail_n, errors, full, cost, sql_index):
    """Display the SQL query log in a formatted table.

    Shows recent SQL queries generated by datasight. Use --sql N to print
    one raw SQL statement for copy/paste into DuckDB, SQLite, or another
    SQL client.
    """
    from rich import box
    from rich.console import Console
    from rich.table import Table
    from rich.text import Text

    from datasight.query_log import QueryLogger

    project_dir = str(Path(project_dir).resolve())
    log_path = os.path.join(project_dir, ".datasight", "query_log.jsonl")

    if not os.path.exists(log_path):
        click.echo(f"No query log found at {log_path}")
        return

    ql = QueryLogger(path=log_path)
    entries = ql.read_recent(tail_n)

    if errors:
        entries = [e for e in entries if e.get("error")]

    if not entries:
        click.echo("No matching log entries.")
        return

    # --sql N: print raw SQL for the Nth most recent query and exit
    if sql_index is not None:
        query_only = [e for e in entries if e.get("type") != "cost" and e.get("sql")]
        if not query_only:
            click.echo("No SQL queries in log.")
            return
        if sql_index < 1 or sql_index > len(query_only):
            click.echo(f"Index out of range. Use 1–{len(query_only)}.")
            return
        entry = query_only[sql_index - 1]
        sql = entry["sql"].strip()
        if not sql.endswith(";"):
            sql += ";"
        click.echo(sql)
        return

    # Separate query entries from cost entries
    query_entries = [e for e in entries if e.get("type") != "cost"]
    cost_entries = [e for e in entries if e.get("type") == "cost"]

    console = Console()
    table = Table(box=box.ROUNDED)
    table.add_column("#", justify="right", style="dim", no_wrap=True)
    table.add_column("Timestamp", style="dim", no_wrap=True)
    table.add_column("Tool", no_wrap=True)
    table.add_column("SQL", min_width=40, overflow="fold")
    table.add_column("Time", justify="right", no_wrap=True)
    table.add_column("Rows", justify="right", no_wrap=True)
    table.add_column("Status", no_wrap=True)

    if full:
        table.add_column("Question", overflow="fold")

    total = len(query_entries)
    failed = 0
    for i, entry in enumerate(query_entries):
        ts = entry.get("timestamp", "")
        # Trim to seconds, drop timezone
        if "T" in ts:
            ts = ts.replace("T", " ")[:19]

        tool = entry.get("tool", "")
        sql = entry.get("sql", "")
        if not full and len(sql) > 120:
            sql = sql[:120] + " ..."

        elapsed = entry.get("execution_time_ms")
        time_str = f"{elapsed:.0f}ms" if elapsed is not None else ""

        row_count = entry.get("row_count")
        rows_str = str(row_count) if row_count is not None else ""

        error = entry.get("error")
        if error:
            failed += 1
            status = Text("ERR", style="bold red")
        else:
            status = Text("OK", style="green")

        sql_id = str(i + 1)
        row = [sql_id, ts, tool, sql, time_str, rows_str, status]
        if full:
            row.append(entry.get("user_question", ""))
        table.add_row(*row)

    console.print(table)

    succeeded = total - failed
    summary = f"{total} queries ({succeeded} succeeded, {failed} failed)"
    console.print(f"\n[dim]{summary}[/dim]")

    # Show cost summary when --cost is used
    if cost and cost_entries:
        cost_table = Table(title="LLM Cost Summary", box=box.ROUNDED)
        cost_table.add_column("Timestamp", style="dim", no_wrap=True)
        cost_table.add_column("Question", overflow="fold")
        cost_table.add_column("API Calls", justify="right", no_wrap=True)
        cost_table.add_column("Input Tokens", justify="right", no_wrap=True)
        cost_table.add_column("Output Tokens", justify="right", no_wrap=True)
        cost_table.add_column("Est. Cost", justify="right", no_wrap=True)

        total_cost = 0.0
        total_input = 0
        total_output = 0
        for entry in cost_entries:
            ts = entry.get("timestamp", "")
            if "T" in ts:
                ts = ts.replace("T", " ")[:19]
            question = entry.get("user_question", "")
            api_calls_n = entry.get("api_calls", 0)
            inp = entry.get("input_tokens", 0)
            out = entry.get("output_tokens", 0)
            cost = entry.get("estimated_cost")
            cost_str = f"${cost:.4f}" if cost is not None else ""
            if cost:
                total_cost += cost
            total_input += inp
            total_output += out
            cost_table.add_row(
                ts,
                question,
                str(api_calls_n),
                f"{inp:,}",
                f"{out:,}",
                cost_str,
            )

        console.print()
        console.print(cost_table)
        cost_summary = f"Totals: {total_input:,} input tokens, {total_output:,} output tokens"
        if total_cost > 0:
            cost_summary += f", ${total_cost:.4f} estimated cost"
        console.print(f"\n[dim]{cost_summary}[/dim]")
